---
# tasks file for install_driver_for_ranger

- name: Install postgres-jdbc driver
  command: yum install -y postgresql-jdbc*
  
- name: Rename driver 
  copy:
    src: "{{ src_name }}" 
    dest: "{{ dest_name }}"

- name: Change the access mode 
  file:
    path: "{{ dest_name }}"
    mode: "644"

- name: Restart PostgreSQL
  systemd:
    state: restarted
    name: postgresql-10.service
    enabled: yes 
