---
# tasks file for deploy_apache

- name: Install apache
  yum:
    name: httpd
    state: latest

- name: Add parcels in config apache
  command: sed -i 's/AddType application\/x-gzip .gz .tgz/AddType application\/x-gzip .gz .tgz .parcel/' "{{ config_file }}"

- name: Start apache
  systemd:
    state: restarted
    name: httpd
    enabled: yes

- name: Disable ipv6
  shell: echo 'net.ipv6.conf.all.disable_ipv6 = 1' >> "{{ sysctl_conf }}";  echo 'net.ipv6.conf.default.disable_ipv6 = 1' >> "{{ sysctl_conf }}"

- name: Accept options
  command: sysctl -p
